# Generated by Django 5.2.6 on 2025-10-02 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LossCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='Número de referência')),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da perda')),
                ('compensation_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da compensação')),
                ('loss_status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('loss_type', models.CharField(choices=[('OPERATIONAL', 'Operacional'), ('FINANCIAL', 'Financeira'), ('TECHNICAL', 'Técnica'), ('OTHER', 'Outros')], max_length=20, verbose_name='Tipo de perda')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('loss_date', models.DateField(verbose_name='Data da perda')),
                ('approval_deadline', models.DateField(blank=True, null=True, verbose_name='Prazo para aprovação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_compensations', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_compensations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Perda de Compensação',
                'verbose_name_plural': 'Perdas de Compensação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'loss_status'], name='perdcomps_l_client__340615_idx'), models.Index(fields=['reference_number'], name='perdcomps_l_referen_a84849_idx'), models.Index(fields=['created_at'], name='perdcomps_l_created_87b27a_idx'), models.Index(fields=['loss_date'], name='perdcomps_l_loss_da_58c53f_idx')],
            },
        ),
    ]
