# Generated by Django 5.2.6 on 2025-10-02 23:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerDcomp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.BigIntegerField(help_text='ID do cliente relacionado')),
                ('created_by_id', models.BigIntegerField(help_text='ID do usuário que criou')),
                ('cnpj', models.CharField(help_text='CNPJ do cliente', max_length=18)),
                ('numero', models.TextField(help_text='Número do documento')),
                ('numero_perdcomp', models.TextField(help_text='Número específico do PER/DCOMP')),
                ('processo_protocolo', models.BigIntegerField(help_text='Número do protocolo do processo')),
                ('data_transmissao', models.DateTimeField(blank=True, help_text='Data e hora da transmissão', null=True)),
                ('data_vencimento', models.DateTimeField(help_text='Data e hora do vencimento')),
                ('data_competencia', models.DateTimeField(help_text='Data da competência')),
                ('tributo_pedido', models.TextField(help_text='Tributo do pedido')),
                ('competencia', models.TextField(help_text='Competência do tributo')),
                ('valor_pedido', models.CharField(help_text='Valor solicitado no pedido', max_length=50)),
                ('valor_compensado', models.CharField(help_text='Valor compensado', max_length=50)),
                ('valor_recebido', models.CharField(help_text='Valor efetivamente recebido', max_length=50)),
                ('valor_saldo', models.CharField(help_text='Valor do saldo remanescente', max_length=50)),
                ('valor_selic', models.CharField(help_text='Valor dos juros SELIC', max_length=50)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('TRANSMITIDO', 'Transmitido'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('PARCIALMENTE_DEFERIDO', 'Parcialmente Deferido'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='RASCUNHO', help_text='Status atual do PER/DCOMP', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Registro ativo no sistema')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PER/DCOMP',
                'verbose_name_plural': 'PER/DCOMPs',
                'db_table': 'perdcomps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='perdcomps_public__d3da07_idx'), models.Index(fields=['numero_perdcomp'], name='perdcomps_numero__45eb6e_idx'), models.Index(fields=['processo_protocolo'], name='perdcomps_process_bfa33d_idx'), models.Index(fields=['cnpj'], name='perdcomps_cnpj_2bbfc2_idx'), models.Index(fields=['client_id'], name='perdcomps_client__e3e118_idx'), models.Index(fields=['status'], name='perdcomps_status_76a02b_idx'), models.Index(fields=['created_at'], name='perdcomps_created_ec18a8_idx'), models.Index(fields=['data_vencimento'], name='perdcomps_data_ve_b6f362_idx'), models.Index(fields=['data_competencia'], name='perdcomps_data_co_fcf11e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerDcompAnnotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('perdcomp_id', models.BigIntegerField(help_text='ID do PER/DCOMP relacionado')),
                ('user_id', models.BigIntegerField(help_text='ID do usuário que fez a anotação')),
                ('content', models.TextField(help_text='Conteúdo da anotação')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perdcomp_annotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='perdcomp_an_public__27b5f5_idx'), models.Index(fields=['perdcomp_id'], name='perdcomp_an_perdcom_5999c3_idx'), models.Index(fields=['user_id'], name='perdcomp_an_user_id_0db5f0_idx'), models.Index(fields=['created_at'], name='perdcomp_an_created_32899f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerDcompAttachedFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('perdcomp_id', models.BigIntegerField(help_text='ID do PER/DCOMP relacionado')),
                ('uploaded_by_id', models.BigIntegerField(help_text='ID do usuário que fez o upload')),
                ('tipo_arquivo', models.CharField(choices=[('PERDCOMP', 'PER/DCOMP'), ('AVISO_RECEBIMENTO', 'Aviso de Recebimento'), ('RECIBO', 'Recibo')], help_text='Tipo do arquivo anexado', max_length=20)),
                ('file_name', models.CharField(help_text='Nome do arquivo', max_length=255)),
                ('file_url', models.URLField(help_text='URL do arquivo no servidor')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='Tipo MIME do arquivo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição do arquivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perdcomp_attached_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='perdcomp_at_public__738df7_idx'), models.Index(fields=['perdcomp_id'], name='perdcomp_at_perdcom_af27fc_idx'), models.Index(fields=['uploaded_by_id'], name='perdcomp_at_uploade_25b5f4_idx'), models.Index(fields=['tipo_arquivo'], name='perdcomp_at_tipo_ar_cd3d5a_idx'), models.Index(fields=['created_at'], name='perdcomp_at_created_b3153d_idx'), models.Index(fields=['file_type'], name='perdcomp_at_file_ty_bb1bd1_idx')],
            },
        ),
    ]
