# Generated by Django 5.2.6 on 2025-10-03 23:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerDcomp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.BigIntegerField(help_text='ID do cliente relacionado')),
                ('created_by_id', models.BigIntegerField(help_text='ID do usuário que criou')),
                ('cnpj', models.CharField(help_text='CNPJ do cliente', max_length=18)),
                ('numero', models.TextField(help_text='Número do documento')),
                ('numero_perdcomp', models.TextField(help_text='Número específico do PER/DCOMP')),
                ('processo_protocolo', models.BigIntegerField(help_text='Número do protocolo do processo')),
                ('data_transmissao', models.DateTimeField(blank=True, help_text='Data e hora da transmissão', null=True)),
                ('data_vencimento', models.DateTimeField(help_text='Data e hora do vencimento')),
                ('data_competencia', models.DateTimeField(help_text='Data da competência')),
                ('tributo_pedido', models.TextField(help_text='Tributo do pedido')),
                ('competencia', models.TextField(help_text='Competência do tributo')),
                ('valor_pedido', models.CharField(help_text='Valor solicitado no pedido', max_length=50)),
                ('valor_compensado', models.CharField(help_text='Valor compensado', max_length=50)),
                ('valor_recebido', models.CharField(help_text='Valor efetivamente recebido', max_length=50)),
                ('valor_saldo', models.CharField(help_text='Valor do saldo remanescente', max_length=50)),
                ('valor_selic', models.CharField(help_text='Valor dos juros SELIC', max_length=50)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('TRANSMITIDO', 'Transmitido'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('PARCIALMENTE_DEFERIDO', 'Parcialmente Deferido'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='RASCUNHO', help_text='Status atual do PER/DCOMP', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Registro ativo no sistema')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PER/DCOMP',
                'verbose_name_plural': 'PER/DCOMPs',
                'db_table': 'perdcomps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='perdcomps_public__d3da07_idx'), models.Index(fields=['numero_perdcomp'], name='perdcomps_numero__45eb6e_idx'), models.Index(fields=['processo_protocolo'], name='perdcomps_process_bfa33d_idx'), models.Index(fields=['cnpj'], name='perdcomps_cnpj_2bbfc2_idx'), models.Index(fields=['client_id'], name='perdcomps_client__e3e118_idx'), models.Index(fields=['status'], name='perdcomps_status_76a02b_idx'), models.Index(fields=['created_at'], name='perdcomps_created_ec18a8_idx'), models.Index(fields=['data_vencimento'], name='perdcomps_data_ve_b6f362_idx'), models.Index(fields=['data_competencia'], name='perdcomps_data_co_fcf11e_idx')],
            },
        ),
    ]
