# Generated by Django 5.2.8 on 2025-11-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdcomp',
            name='numero_perdcomp',
            field=models.TextField(blank=True, help_text='Número específico do PER/DCOMP', null=True),
        ),
    ]
