# Generated by Django 5.2.6 on 2025-10-01 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_clients_status_98ee60_idx_and_more'),
        ('perdcomps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='losscompensation',
            name='perdcomps_l_client__192b94_idx',
        ),
        migrations.RenameField(
            model_name='losscompensation',
            old_name='status',
            new_name='loss_status',
        ),
        migrations.AddIndex(
            model_name='losscompensation',
            index=models.Index(fields=['client', 'loss_status'], name='perdcomps_l_client__340615_idx'),
        ),
    ]
