# Generated by Django 5.2.8 on 2025-11-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomps', '0002_alter_perdcomp_numero_perdcomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdcomp',
            name='processo_protocolo',
            field=models.TextField(blank=True, help_text='Protocolo do processo (texto)', null=True),
        ),
    ]
