# Generated by Django 5.2.8 on 2025-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomps', '0003_alter_perdcomp_processo_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdcomp',
            name='data_competencia',
            field=models.DateField(help_text='Data da competência'),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='data_transmissao',
            field=models.DateField(blank=True, help_text='Data da transmissão', null=True),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='data_vencimento',
            field=models.DateField(help_text='Data do vencimento'),
        ),
    ]
