# Generated by Django 5.2.8 on 2025-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomps', '0004_alter_perdcomp_data_competencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdcomp',
            name='data_competencia',
            field=models.DateField(blank=True, help_text='Data da competência', null=True),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data do vencimento', null=True),
        ),
    ]
