# Generated by Django 5.2.8 on 2025-12-09 13:16

import apps.perdcomps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomps', '0005_alter_perdcomp_data_competencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdcomp',
            name='competencia',
            field=models.TextField(blank=True, help_text='Competência do tributo', null=True),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='data_transmissao',
            field=models.DateField(default=apps.perdcomps.models.get_current_date, help_text='Data da transmissão'),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='data_vencimento',
            field=models.DateField(default=apps.perdcomps.models.get_current_date, help_text='Data do vencimento'),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='numero',
            field=models.TextField(blank=True, help_text='Número do documento', null=True),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='numero_perdcomp',
            field=models.TextField(default=apps.perdcomps.models.get_default_numero_perdcomp, help_text='Número específico do PER/DCOMP'),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='valor_compensado',
            field=models.CharField(blank=True, help_text='Valor compensado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='valor_recebido',
            field=models.CharField(blank=True, help_text='Valor efetivamente recebido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='valor_saldo',
            field=models.CharField(blank=True, help_text='Valor do saldo remanescente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perdcomp',
            name='valor_selic',
            field=models.CharField(blank=True, help_text='Valor dos juros SELIC', max_length=50, null=True),
        ),
    ]
