# Generated by Django 5.2.8 on 2026-10-02 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_selic_report_type'),
        ('perdcomps', '0007_alter_perdcomp_status_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentaryCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_protocol', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.JSONField(default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('protocol', models.CharField(max_length=24)),
                ('protocol_original', models.CharField(max_length=40)),
                ('modality', models.CharField(max_length=30)),
                ('revision_kind', models.CharField(max_length=16)),
                ('completeness', models.CharField(max_length=30)),
                ('fiscal_status', models.CharField(default='nao_consultada', editable=False, max_length=24)),
                ('financial_effect', models.CharField(default='nao_aplicado', editable=False, max_length=24)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perdcomps.documentarycredit')),
                ('legacy_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perdcomps.perdcomp')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('applied', models.BooleanField(default=False, editable=False)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='perdcomps.importeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perdcomps.importbatch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='perdcomps.importeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('target_protocol', models.CharField(max_length=24)),
                ('legacy_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perdcomps.perdcomp')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='perdcomps.importeddocument')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='perdcomps.importeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('data', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='perdcomps.importeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCreditComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('assessed', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('previous_use', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('used', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('data', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='perdcomps.importeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('decision', 'decision'), ('installment', 'installment'), ('liquidation', 'liquidation'), ('official_consultation', 'official_consultation'), ('calculation', 'calculation')], max_length=24)),
                ('event_key', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ('data', models.JSONField(default=dict)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perdcomps.documentaryevent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perdcomps.importeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=20)),
                ('pages', models.PositiveSmallIntegerField()),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('original_content', models.BinaryField(null=True)),
                ('parser_version', models.CharField(max_length=40)),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extraction', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perdcomps.importbatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='perdcomps.importeddocument')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentarycredit',
            constraint=models.UniqueConstraint(fields=('client', 'origin_protocol'), name='unique_documentary_credit'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('client', 'fingerprint'), name='unique_documentary_batch'),
        ),
        migrations.AddConstraint(
            model_name='importeddocument',
            constraint=models.UniqueConstraint(fields=('cnpj', 'protocol'), name='unique_documentary_identity'),
        ),
        migrations.AddConstraint(
            model_name='documentrelation',
            constraint=models.UniqueConstraint(fields=('source', 'kind', 'target_protocol'), name='unique_documentary_relation'),
        ),
        migrations.AddConstraint(
            model_name='documentdebt',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='unique_documentary_debt'),
        ),
        migrations.AddConstraint(
            model_name='documentcreditcomponent',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='unique_documentary_component'),
        ),
        migrations.AddConstraint(
            model_name='documentaryevent',
            constraint=models.UniqueConstraint(fields=('document', 'kind', 'event_key'), name='unique_documentary_event'),
        ),
        migrations.AddConstraint(
            model_name='importedfile',
            constraint=models.UniqueConstraint(fields=('client', 'sha256'), name='unique_documentary_file'),
        ),
    ]
