# Generated by Django 5.2.8 on 2026-10-02 20:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_selic_report_type'),
        ('perdcomps', '0008_documentarycredit_importbatch_importeddocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('pages', models.PositiveSmallIntegerField(default=0)),
                ('original_content', models.BinaryField()),
                ('extraction', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('resolved', 'Tratado'), ('dismissed', 'Descartado')], default='pending', max_length=16)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perdcomps.importbatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_manual_import_issues', to=settings.AUTH_USER_MODEL)),
                ('operational_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perdcomps.perdcomp')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_manual_import_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'sha256'), name='unique_manual_import_file')],
            },
        ),
    ]
