# Generated by Django 5.2.8 on 2026-10-04 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomps', '0009_manualimportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='superseded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_documents', to='perdcomps.importeddocument'),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='version_status',
            field=models.CharField(choices=[('current', 'Versão vigente'), ('superseded', 'Substituída'), ('previous', 'Versão anterior — nenhum dado alterado'), ('cancelled', 'Cancelada')], default='current', max_length=16),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='credito_original_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='saldo_a_receber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='saldo_credito_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='status_compensacao',
            field=models.CharField(choices=[('NAO_APLICAVEL', 'Não aplicável'), ('DECLARADA_AGUARDANDO_HOMOLOGACAO', 'Declarada, aguardando homologação'), ('EM_PROCESSAMENTO', 'Em processamento'), ('HOMOLOGADA_INTEGRALMENTE', 'Homologada integralmente'), ('HOMOLOGADA_PARCIALMENTE', 'Homologada parcialmente'), ('NAO_HOMOLOGADA', 'Não homologada'), ('RETIFICADA', 'Retificada'), ('CANCELADA', 'Cancelada'), ('REVISAO_MANUAL', 'Revisão manual')], default='NAO_APLICAVEL', max_length=48),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='status_ressarcimento',
            field=models.CharField(choices=[('NAO_APLICAVEL', 'Não aplicável'), ('SOLICITADO', 'Solicitado'), ('EM_PROCESSAMENTO', 'Em processamento'), ('DEFERIDO_AGUARDANDO_PAGAMENTO', 'Deferido, aguardando pagamento'), ('PAGAMENTO_AUTORIZADO_AGUARDANDO_CONCILIACAO', 'Pagamento autorizado, aguardando conciliação'), ('RECEBIDO', 'Recebido'), ('RECEBIDO_PARCIALMENTE', 'Recebido parcialmente'), ('COMPENSADO_DE_OFICIO', 'Compensado de ofício'), ('DEFERIDO_PARCIALMENTE', 'Deferido parcialmente'), ('INDEFERIDO', 'Indeferido'), ('REVISAO_MANUAL', 'Revisão manual')], default='NAO_APLICAVEL', max_length=56),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_versions', to='perdcomps.perdcomp'),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='valor_compensado_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='valor_compensado_homologado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='valor_compensado_oficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='valor_deferido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='valor_pagamento_autorizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='valor_recebido_banco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='valor_solicitado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='perdcomp',
            name='version_status',
            field=models.CharField(choices=[('VIGENTE', 'Versão vigente'), ('SUBSTITUIDA', 'Substituída'), ('VERSAO_ANTERIOR', 'Versão anterior — nenhum dado alterado'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=24),
        ),
    ]
