# Generated by Django 5.2.8 on 2026-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomps', '0010_importeddocument_superseded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedfile',
            name='database_released_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='importedfile',
            name='drive_md5',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='importedfile',
            name='drive_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='importedfile',
            name='drive_synced_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='manualimportissue',
            name='database_released_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='manualimportissue',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manualimportissue',
            name='drive_md5',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='manualimportissue',
            name='drive_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='manualimportissue',
            name='drive_synced_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='importedfile',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manualimportissue',
            name='original_content',
            field=models.BinaryField(null=True),
        ),
    ]
