# Generated by Django 5.2.6 on 2025-10-03 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('user_id', models.BigIntegerField(help_text='ID do usuário que criou a anotação')),
                ('content', models.TextField(help_text='Conteúdo da anotação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'common_annotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_anno_content_882665_idx'), models.Index(fields=['user_id'], name='common_anno_user_id_831730_idx'), models.Index(fields=['created_at'], name='common_anno_created_8b259d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('file_type', models.CharField(help_text='Tipo do arquivo (específico por entidade)', max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField(help_text='Tamanho do arquivo em bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by_id', models.BigIntegerField(help_text='ID do usuário que fez o upload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'common_attached_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_atta_content_ba4c06_idx'), models.Index(fields=['file_type'], name='common_atta_file_ty_57211f_idx'), models.Index(fields=['uploaded_by_id'], name='common_atta_uploade_7d074a_idx'), models.Index(fields=['created_at'], name='common_atta_created_039b8a_idx')],
            },
        ),
    ]
