# Generated by Django 5.2.8 on 2025-11-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Conteúdo da anotação em formato JSON'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user_id', 'content_type', 'object_id'), name='unique_user_entity_annotation'),
        ),
    ]
