# Generated by Django 5.2.8 on 2025-11-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_annotation_content_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annotation',
            name='unique_user_entity_annotation',
        ),
    ]
