# Generated by Django 5.2.8 on 2025-12-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_remove_annotation_unique_user_entity_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='deleted_at',
        ),
    ]
