# Generated by Django 5.2.8 on 2025-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shared', '0004_remove_attachedfile_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='download_link',
            field=models.URLField(blank=True, help_text='Link direto para download', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='drive_file_id',
            field=models.CharField(default='pending_upload', help_text='ID único do arquivo no Google Drive', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='ID da pasta pai no Google Drive', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, help_text='Última verificação de existência no Drive', null=True),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='sync_status',
            field=models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('error', 'Erro na Sincronização')], default='synced', help_text='Status de sincronização com Google Drive', max_length=20),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='web_view_link',
            field=models.URLField(blank=True, help_text='Link para visualização no navegador', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='attachedfile',
            index=models.Index(fields=['drive_file_id'], name='common_atta_drive_f_e5f5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='attachedfile',
            index=models.Index(fields=['sync_status'], name='common_atta_sync_st_9c1cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='attachedfile',
            index=models.Index(fields=['last_verified_at'], name='common_atta_last_ve_85e356_idx'),
        ),
    ]
