# Generated by Django 5.2.8 on 2025-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_remove_attachedfile_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachedfile',
            name='common_atta_created_039b8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='attachedfile',
            name='common_atta_last_ve_85e356_idx',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='drive_folder_id',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='last_verified_at',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='web_view_link',
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='file_name',
            field=models.CharField(help_text='Nome original do arquivo', max_length=255),
        ),
    ]
