# Generated by Django 5.2.8 on 2025-12-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_remove_attachedfile_common_atta_created_039b8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfile',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição opcional do arquivo', null=True),
        ),
    ]
