# Generated by Django 5.2.8 on 2025-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_attachedfile_description'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachedfile',
            name='common_atta_uploade_7d074a_idx',
        ),
        migrations.RemoveIndex(
            model_name='attachedfile',
            name='common_atta_sync_st_9c1cb1_idx',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='sync_status',
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', help_text='Tipo MIME para o navegador (ex: application/pdf)', max_length=100),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição opcional para o usuário', null=True),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='drive_file_id',
            field=models.CharField(help_text='ID do arquivo no Google Drive (Service Account)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='file_name',
            field=models.CharField(help_text='Nome original do arquivo (ex: scan.pdf)', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='file_size',
            field=models.PositiveBigIntegerField(help_text='Tamanho em bytes'),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='file_type',
            field=models.CharField(help_text='Categoria de negócio (ex: contrato, recibo). Validado via Serializer.', max_length=50),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='uploaded_by_id',
            field=models.BigIntegerField(help_text='ID do usuário que fez upload'),
        ),
    ]
