# Generated by Django 5.2.8 on 2025-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_remove_attachedfile_common_atta_uploade_7d074a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados extras condicionais (ex: data de validade para contratos)'),
        ),
    ]
