# Generated by Django 5.2.6 on 2025-10-03 23:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logradouro', models.CharField(help_text='Logradouro', max_length=255)),
                ('numero', models.CharField(help_text='Número', max_length=20)),
                ('complemento', models.CharField(blank=True, help_text='Complemento', max_length=255)),
                ('bairro', models.CharField(help_text='Bairro', max_length=100)),
                ('municipio', models.CharField(help_text='Município', max_length=100)),
                ('uf', models.CharField(help_text='UF', max_length=2)),
                ('cep', models.CharField(help_text='CEP', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='addresses_public__7fb800_idx'), models.Index(fields=['cep'], name='addresses_cep_cc8c6f_idx'), models.Index(fields=['municipio'], name='addresses_municip_c735ae_idx'), models.Index(fields=['uf'], name='addresses_uf_628c84_idx')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(help_text='Razão social do cliente', max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome fantasia do cliente', max_length=255)),
                ('cnpj', models.CharField(help_text='CNPJ do cliente', max_length=18, unique=True)),
                ('inscricao_estadual', models.TextField(blank=True, help_text='Inscrição estadual')),
                ('inscricao_municipal', models.TextField(blank=True, help_text='Inscrição municipal')),
                ('tipo_empresa', models.TextField(blank=True, help_text='Tipo da empresa')),
                ('recuperacao_judicial', models.BooleanField(default=False, help_text='Em recuperação judicial')),
                ('telefone_comercial', models.TextField(blank=True, help_text='Telefone comercial')),
                ('email_comercial', models.CharField(blank=True, help_text='Email comercial', max_length=255)),
                ('website', models.TextField(blank=True, help_text='Website da empresa')),
                ('telefone_contato', models.TextField(blank=True, help_text='Telefone de contato')),
                ('email_contato', models.TextField(blank=True, help_text='Email de contato')),
                ('quadro_societario', models.JSONField(blank=True, default=list, help_text='Quadro societário (lista de sócios)')),
                ('cargos', models.JSONField(blank=True, default=dict, help_text='Cargos e responsabilidades')),
                ('responsavel_financeiro', models.TextField(blank=True, help_text='Responsável financeiro')),
                ('contador_responsavel', models.TextField(blank=True, help_text='Contador responsável')),
                ('cnaes', models.JSONField(blank=True, default=list, help_text='CNAEs da empresa')),
                ('regime_tributacao', models.CharField(blank=True, choices=[('lucro_real', 'Lucro Real'), ('lucro_presumido', 'Lucro Presumido')], help_text='Regime de tributação', max_length=20)),
                ('contrato_social', models.TextField(blank=True, help_text='Dados do contrato social')),
                ('ultima_alteracao_contratual', models.DateTimeField(blank=True, help_text='Data da última alteração contratual', null=True)),
                ('rg_cpf_socios', models.TextField(blank=True, help_text='RG/CPF dos sócios')),
                ('certificado_digital', models.TextField(blank=True, help_text='Informações do certificado digital')),
                ('autorizado_para_envio', models.BooleanField(default=False, help_text='Autorizado para envio')),
                ('atividades', models.JSONField(blank=True, default=dict, help_text='Atividades da empresa')),
                ('client_status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('archived', 'Arquivado')], default='pending', help_text='Status do cliente', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Cliente ativo no sistema')),
                ('address_id', models.BigIntegerField(blank=True, help_text='ID do endereço do cliente', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='clients_public__821dbf_idx'), models.Index(fields=['cnpj'], name='clients_cnpj_9d3a8e_idx'), models.Index(fields=['client_status'], name='clients_client__e9501d_idx'), models.Index(fields=['is_active'], name='clients_is_acti_43299d_idx'), models.Index(fields=['created_at'], name='clients_created_4c189f_idx'), models.Index(fields=['address_id'], name='clients_address_f1e342_idx')],
            },
        ),
    ]
