# Generated by Django 5.2.6 on 2025-10-01 15:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(help_text='CNPJ do cliente', max_length=18, unique=True)),
                ('razao_social', models.CharField(help_text='Razão social do cliente', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('archived', 'Arquivado')], default='pending', help_text='Status do cliente', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Cliente ativo no sistema')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome fantasia do cliente', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email de contato', max_length=254)),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20)),
                ('annotations', models.TextField(blank=True, help_text='Anotações internas sobre o cliente')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cnpj'], name='clients_cnpj_9d3a8e_idx'), models.Index(fields=['status'], name='clients_status_98ee60_idx'), models.Index(fields=['is_active'], name='clients_is_acti_43299d_idx'), models.Index(fields=['created_at'], name='clients_created_4c189f_idx')],
            },
        ),
    ]
