# Generated by Django 5.2.6 on 2025-10-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Cliente ativo no sistema', null=True),
        ),
    ]
