# Generated by Django 5.2.6 on 2025-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_status_98ee60_idx',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='status',
            new_name='client_status',
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_status'], name='clients_client__e9501d_idx'),
        ),
    ]
