# Generated by Django 5.2.6 on 2025-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('archived', 'Arquivado')], default='pending', help_text='Status do cliente', max_length=20, null=True),
        ),
    ]
