# Generated by Django 5.2.8 on 2025-11-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_client_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_address_f1e342_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address_id',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.OneToOneField(blank=True, help_text='Endereço do cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='logradouro',
            field=models.CharField(blank=True, help_text='Logradouro', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipio',
            field=models.CharField(blank=True, help_text='Município', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='numero',
            field=models.CharField(blank=True, help_text='Número', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='uf',
            field=models.CharField(blank=True, help_text='UF', max_length=2),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['address'], name='clients_address_f1e342_idx'),
        ),
    ]
