# Generated by Django 5.2.8 on 2025-11-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_clients_address_f1e342_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='deleted_at',
        ),
    ]
