# Generated by Django 5.2.8 on 2025-11-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_address_soft_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cargos',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cnaes',
        ),
        migrations.AlterField(
            model_name='client',
            name='atividades',
            field=models.JSONField(blank=True, default=list, help_text="Atividades da empresa - lista com CNAE e descrição: [{'cnae': 'Código CNAE', 'descricao': 'Descrição da atividade'}]"),
        ),
        migrations.AlterField(
            model_name='client',
            name='quadro_societario',
            field=models.JSONField(blank=True, default=list, help_text="Quadro societário - lista com nome e cargo de cada sócio: [{'nome': 'Nome do Sócio', 'cargo': 'Cargo/Função'}]"),
        ),
    ]
