# Generated by Django 5.2.8 on 2025-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_cargos_remove_client_cnaes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='certificado_digital',
            field=models.TextField(blank=True, help_text='Informações do certificado digital', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contador_responsavel',
            field=models.TextField(blank=True, help_text='Contador responsável', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contrato_social',
            field=models.TextField(blank=True, help_text='Dados do contrato social', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_comercial',
            field=models.CharField(blank=True, help_text='Email comercial', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_contato',
            field=models.TextField(blank=True, help_text='Email de contato', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='inscricao_estadual',
            field=models.TextField(blank=True, help_text='Inscrição estadual', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='inscricao_municipal',
            field=models.TextField(blank=True, help_text='Inscrição municipal', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome fantasia do cliente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='quadro_societario',
            field=models.JSONField(blank=True, default=list, help_text="Quadro societário - lista com nome e cargo de cada sócio: [{'nome': 'Nome do Sócio', 'cargo': 'Cargo/Função'}]", null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='regime_tributacao',
            field=models.CharField(blank=True, choices=[('lucro_real', 'Lucro Real'), ('lucro_presumido', 'Lucro Presumido')], help_text='Regime de tributação', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='responsavel_financeiro',
            field=models.TextField(blank=True, help_text='Responsável financeiro', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg_cpf_socios',
            field=models.TextField(blank=True, help_text='RG/CPF dos sócios', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone_comercial',
            field=models.TextField(blank=True, help_text='Telefone comercial', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone_contato',
            field=models.TextField(blank=True, help_text='Telefone de contato', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.TextField(blank=True, help_text='Website da empresa', null=True),
        ),
    ]
