# Generated by Django 5.2.8 on 2025-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_make_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('archived', 'Arquivado')], default='active', help_text='Status do cliente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ultima_alteracao_contratual',
            field=models.DateField(blank=True, help_text='Data da última alteração contratual', null=True),
        ),
    ]
