# Generated by Django 5.2.6 on 2025-10-01 15:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text="Assunto da solicitação (ex: 'Ativar cliente XYZ')", max_length=255)),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('activate', 'Ativar'), ('deactivate', 'Desativar'), ('custom', 'Ação Personalizada')], help_text='Tipo de ação a ser executada', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('executed', 'Executado'), ('cancelled', 'Cancelado')], default='pending', help_text='Status atual da solicitação', max_length=20)),
                ('resource_type', models.CharField(help_text="Tipo do recurso a ser modificado (ex: 'clients.Client')", max_length=100)),
                ('resource_id', models.CharField(help_text='ID do recurso a ser modificado', max_length=255)),
                ('payload_diff', models.JSONField(help_text='Diferença dos dados (antes/depois da mudança)')),
                ('reason', models.TextField(help_text='Motivo da solicitação')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento da criação da solicitação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Momento da última atualização')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Momento da aprovação/rejeição', null=True)),
                ('executed_at', models.DateTimeField(blank=True, help_text='Momento da execução da mudança', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre a solicitação')),
                ('approval_notes', models.TextField(blank=True, help_text='Notas do aprovador')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Usuário que aprovou/rejeitou a solicitação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Usuário que fez a solicitação', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='approval_re_status_293063_idx'), models.Index(fields=['requested_by'], name='approval_re_request_2f1892_idx'), models.Index(fields=['approved_by'], name='approval_re_approve_6ed597_idx'), models.Index(fields=['resource_type', 'resource_id'], name='approval_re_resourc_71c132_idx'), models.Index(fields=['created_at'], name='approval_re_created_1a1d31_idx')],
            },
        ),
    ]
