# Generated by Django 5.2.6 on 2025-10-02 22:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(help_text="Assunto da solicitação (ex: 'Ativar cliente XYZ')", max_length=255)),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('activate', 'Ativar'), ('deactivate', 'Desativar'), ('custom', 'Ação Personalizada')], help_text='Tipo de ação a ser executada', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status da solicitação', max_length=20)),
                ('resource_type', models.CharField(help_text="Tipo do recurso a ser modificado (ex: 'clients.Client')", max_length=100)),
                ('resource_id', models.CharField(help_text='ID do recurso a ser modificado', max_length=255)),
                ('payload_diff', models.JSONField(help_text='Diferença dos dados (antes/depois da mudança)')),
                ('reason', models.TextField(help_text='Motivo da solicitação')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento da criação da solicitação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Momento da última atualização')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Momento da aprovação/rejeição', null=True)),
                ('executed_at', models.DateTimeField(blank=True, help_text='Momento da execução da mudança', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre a solicitação')),
                ('approval_notes', models.TextField(blank=True, help_text='Notas do aprovador')),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
