# Generated by Django 5.2.6 on 2025-10-03 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou/rejeitou a solicitação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='Usuário que fez a solicitação', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['public_id'], name='approval_re_public__dc4b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='approval_re_status_293063_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_by'], name='approval_re_request_2f1892_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['approved_by'], name='approval_re_approve_6ed597_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['resource_type', 'resource_id'], name='approval_re_resourc_71c132_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['created_at'], name='approval_re_created_1a1d31_idx'),
        ),
    ]
