# Generated by Django 5.2.8 on 2025-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='was_approved',
            field=models.BooleanField(blank=True, help_text='True se aprovado, False se rejeitado, None se ainda pendente', null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('executed', 'Executado'), ('cancelled', 'Cancelado')], default='pending', help_text='Status da solicitação', max_length=20),
        ),
    ]
