# Generated by Django 5.2.6 on 2025-10-01 13:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(help_text='ID de correlação para rastrear todas as ações de um request')),
                ('action', models.CharField(choices=[('CREATE', 'Criar'), ('UPDATE', 'Atualizar'), ('DELETE', 'Excluir'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVAL_REQUESTED', 'Aprovação Solicitada'), ('APPROVAL_GRANTED', 'Aprovação Concedida'), ('APPROVAL_DENIED', 'Aprovação Negada'), ('CUSTOM', 'Ação Personalizada')], help_text='Tipo de ação realizada (CREATE, UPDATE, DELETE, etc.)', max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('old_data', models.JSONField(blank=True, help_text='Estado anterior do objeto (para UPDATE/DELETE)', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Novo estado do objeto (para CREATE/UPDATE)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre a ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do usuário que executou a ação', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do browser/cliente', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento em que a ação foi executada')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que executou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['correlation_id'], name='audit_logs_correla_953e51_idx'), models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
