# Generated by Django 5.2.6 on 2025-10-03 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(help_text='ID de correlação para rastrear todas as ações de um request')),
                ('action', models.CharField(choices=[('CREATE', 'Criar'), ('UPDATE', 'Atualizar'), ('DELETE', 'Excluir'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVAL_REQUESTED', 'Aprovação Solicitada'), ('APPROVAL_GRANTED', 'Aprovação Concedida'), ('APPROVAL_DENIED', 'Aprovação Negada'), ('CUSTOM', 'Ação Personalizada')], help_text='Tipo de ação realizada (CREATE, UPDATE, DELETE, etc.)', max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('old_data', models.JSONField(blank=True, help_text='Estado anterior do objeto (para UPDATE/DELETE)', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Novo estado do objeto (para CREATE/UPDATE)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre a ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do usuário que executou a ação', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do browser/cliente', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento em que a ação foi executada')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
