# Generated by Django 5.2.6 on 2025-09-19 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("guest", "Guest"),
                    ("admin", "Admin"),
                ],
                default="employee",
                help_text="User role that determines permissions",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SensibleDataChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("email_change", "Email Change"),
                            ("role_change", "Role Change"),
                            ("sensitive_profile_change", "Sensitive Profile Change"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "requested_changes",
                    models.JSONField(help_text="JSON containing the requested changes"),
                ),
                (
                    "justification",
                    models.TextField(help_text="Reason for the change request"),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the review"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensible Data Change Request",
                "verbose_name_plural": "Sensible Data Change Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
